version: '3.3'

volumes:
  static:

services:
  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/backend_static/
  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/