# Generated by Django 4.2.5 on 2023-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lessonproduct",
            constraint=models.UniqueConstraint(
                fields=("product", "lesson"), name="unique_product_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="userlesson",
            constraint=models.UniqueConstraint(
                fields=("user", "lesson"), name="unique_user_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="userproduct",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_user_product"
            ),
        ),
    ]
