name: Qortex workflow

on:
  push:
    branches:
      - main

jobs:
  backend_linter_test:
    name: Test backend code with FLAKE8
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install lint requirements
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements/requirements.lint.txt
    - name: Test with FLAKE8
      run: |
        python -m flake8 backend/.
  backend_project_test:
    name: Test backend code with Django Tests
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install project requirements
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements/requirements.project.txt
    - name: Test with Django Tests
      run: |
        cd backend
        python manage.py test